spring:
  rabbitmq:
    host: 192.168.99.100
    #注意这里不是15672端口
    port: 5672
    username: guest
    password: guest
    # 是否开启生产者回调
    publisher-confirms: true #支持发布确认
    publisher-returns: true #支持发布返回
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true #是否支持重试
logging:
  file: D:/cantong/demo.log
