server:
  port: 8000
  context-path: /demo
  address: 127.0.0.1
message:
  data:
    name: szy
    age : 20
    school : 黄石理工
testStatic:
  data:
    hehe: kkkkkkkkkkkkkk
spring:
#数据源
  datasource:
    url:    jdbc:mysql://123.207.70.54:3306/bootest?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: prouser
    password: '@L20n#everLWLfor1h435S.1ZY'
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: com.mysql.jdbc.Driver
    driverClassName: com.mysql.jdbc.Driver
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x' from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
# redis基础配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 3000
    # redis线程池配置
    pool:
     # 如果赋值为-1，表示不限制；如果pool已经分配了maxActive个jedis实例，则此时的pool状态为exhausted
      max-active: 20
      # 最大的等待时间，毫秒，默认-1，表示永不超时，如果超出等待时间，抛出JedisConnectionException
      max-wait: 1000
      # 连接池中最大的空闲链接，默认8
      max-idle: 100
      # 连接池中最小的空闲链接，默认0
      min-idle: 5
  jpa:
    show-sql: true
    generate-ddl: true
    #每次加载都会在删除数据库和表数据,再从新创建create
    hibernate:
      ddl-auto: validate
  #AMQP 高级消息队列协议
  application:
    name: spring-boot-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: 123456
    # 是否开启生产者回调
    publisher-confirms: true
    virtual-host: /
   #热部署 开发者模式开启，生成模式关闭
  devtools:
    restart:
      enabled: true
  mvc:
    view:
      prefix: /
      suffix: .html
 # mail:
 #   port: 25
  #  username:
  # password:
mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.sun.demo.dto
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  property:
    order: BEFORE
# 打印sql
logging:
  level:
    root : info
    com.sun.demo : debug
#自定义swagger2配置 查看链接http://127.0.0.2:8000/demo/swagger-ui.html
swagger2:
  user-name: szy
  url: http://www.baidu.com
  email: 295508987@qq.com
  title: Swaager2
  desc: Swaager2
  version: 1.0
  license: Apache
  license-url: http://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: www.baidu.com
  base-package: com.sun.demo.controller.api
